version: '3'

tasks:
  default:
    desc: "Build and run the GitHub stats analyzer"
    cmds:
      - task: build
      - task: run

  help:
    desc: "Show available commands and environment variables"
    cmds:
      - |
        echo "GitHub Stats - Available Commands"
        echo "=================================="
        echo ""
        echo "  task run       - Run the PR statistics analyzer"
        echo "  task comments  - Extract comments from a specific user"
        echo "  task viewer    - Open the comments viewer in browser"
        echo "  task build     - Compile TypeScript to JavaScript"
        echo "  task install   - Install dependencies"
        echo "  task clean     - Clean output and build directories"
        echo ""
        echo "Environment Variables"
        echo "====================="
        echo ""
        echo "  TOKEN  - GitHub personal access token (required)"
        echo "  REPO   - Repository to analyze, format: owner/repo (default: pbstck/app)"
        echo "  DAYS   - Number of days to analyze (default: 30)"
        echo "  USER   - Username to extract comments from (required for 'task comments')"
        echo ""
        echo "Examples"
        echo "========"
        echo ""
        echo "  TOKEN=ghp_xxx task run"
        echo "  TOKEN=ghp_xxx REPO=owner/repo DAYS=60 task run"
        echo "  TOKEN=ghp_xxx REPO=owner/repo USER=username task comments"
        echo ""

  install:
    desc: "Install dependencies"
    cmds:
      - pnpm install

  build:
    desc: "Compile TypeScript to JavaScript"
    cmds:
      - pnpm build
    sources:
      - src/**/*.ts
      - tsconfig.json
    generates:
      - dist/**/*.js

  run:
    desc: "Run the GitHub stats analyzer"
    deps:
      - build
    cmds:
      - node dist/index.js

  comments:
    desc: "Extract comments from a specific user"
    deps:
      - build
    cmds:
      - node dist/extract-comments.js

  viewer:
    desc: "Open the comments viewer in browser"
    cmds:
      - echo "Starting server on http://localhost:3333/viewer/"
      - echo "Drag & drop your JSON file to load it"
      - echo "Press Ctrl+C to stop"
      - sleep 1 && (xdg-open http://localhost:3333/viewer/ || open http://localhost:3333/viewer/ || start http://localhost:3333/viewer/) &
      - npx --yes serve . -l 3333

  clean:
    desc: "Clean output and build directories"
    cmds:
      - rm -rf output/
      - rm -rf dist/

  all:
    desc: "Build and run (same as default)"
    cmds:
      - task: build
      - task: run
